name: build-binary
on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: setup go
              uses: actions/setup-go@v2
              with:
                go-version: 1.18
            - name: checkout
              uses: actions/checkout@v2
            - name: solve dependencies
              run: go mod download
            - name: build
              run: go build -o ./bin/qcg-center ./src/main.go
        