name: Release Docker Image

on:
  push:  # 仅修改.go文件时触发
    branches:
      - main
    paths:
      - src/**.go
      - assets/**.json
      - Dockerfile
      - .github/workflows/release-image.yaml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Golang
          uses: actions/setup-go@v2
          with:
            go-version: 1.21
    
        - name: Build Binary
          run: go build -o bin/qcg-center .

        - name: Build
          run: docker build -t rockchin/qcg-center:latest .
    
        - name: Login to Registry
          run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Push to DockerHub
          run: docker push rockchin/qcg-center:latest